### ISSUE TITLE
Chapter 2: Clarify that p4 still needs PoW consensus

### ISSUE THREAD

**Issue by JoshOrndorff** [JoshOrndorff/blockchain-from-scratch#20]
In chapter 2, we introduce simple PoW consensus in p3. We use it again in p5 when learning about fork choice rules. However, p4, that comes in between is very unclear about whether the PoW is necessary. But indeed the **PoW is necessary in p4**.

- [ ] Clarify instructions that PoW is still necessary
- [ ] Provide a `THRESHOLD`. At minimum copy the one from p3. Better yet, put it in a single place (maybe `mod.rs` or maybe just p3) and then import it into the other lessons that use it.
- [ ] Add a test in p4 to make sure the PoW is still working.

**Comment by JoshOrndorff** [comment]
@sheetalojha would you be willing to work on this one?

**Comment by sheetalojha** [comment]
yes! working on it!

**Comment by JoshOrndorff** [comment]
Solved in #21
